name: EcoEnchants
version: ${projectVersion}
main: com.willfp.ecoenchants.EcoEnchantsPlugin
api-version: 1.15
authors: [Auxilor]
website: willfp.com
load: STARTUP
depend:
  - eco
  - ProtocolLib
softdepend:
  - WorldGuard
  - GriefPrevention
  - Towny
  - FactionsUUID
  - Lands
  - Kingdoms
  - NoCheatPlus
  - AAC
  - Matrix
  - Spartan
  - Essentials
  - PlaceholderAPI
  - mcMMO

commands:
  ecoreload:
    description: Reloads config
    permission: ecoenchants.reload
  ecodebug:
    description: Debug information
    permission: ecoenchants.ecodebug
  enchantinfo:
    description: Show information about an enchantment
    permission: ecoenchants.enchantinfo

permissions:
  ecoenchants.*:
    description: All ecoenchants permissions
    default: op
    children:
      ecoenchants.fromtable.*: true
      ecoenchants.reload: true
      ecoenchants.updateannounce: true
      ecoenchants.enchantinfo: true
      ecoenchants.ecodebug: true
      ecoenchants.anvil.*: true
  ecoenchants.anvil.*:
    description: Allows all anvil permissions
    default: op
    children:
      ecoenchants.anvil.bypasshardcap: true
      ecoenchants.anvil.color: true
  ecoenchants.fromtable.*:
    description: Allows getting all enchantments from an enchanting table
    default: true

  ecoenchants.updateannounce:
    description: Informs admins of a new update
    default: op
  ecoenchants.reload:
    description: Allows reloading the config
    default: op
  ecoenchants.ecodebug:
    description: Allows the use of /ecodebug to print verbose debug information to console
    default: op
  ecoenchants.enchantinfo:
    description: Allows the use of /enchantinfo to show enchant info
    default: true
  ecoenchants.anvil.bypasshardcap:
    description: Allows bypassing the anvil hard cap
    default: op
  ecoenchants.anvil.color:
    description: Allows color from anvil renames
    default: op

  # Perks
  ecoenchants.cooldowntime.half:
    description: Halves the cooldown time on spells
    default: false
  ecoenchants.cooldowntime.third:
    description: Thirds the cooldown time on spells
    default: false
  ecoenchants.cooldowntime.quarter:
    description: Quarters the cooldown time on spells
    default: false
  ecoenchants.cooldowntime.75:
    description: Reduces the cooldown time on spells by 25%
    default: false