blank_issues_enabled: false
contact_links:
  - name: Auxilor Community Discord
    url: https://discord.gg/ZcwpSsE/
    about: Join the Auxilor discord to get help from support staff and the general community!
